In [ ]:
import numpy as np
import sympy as sp

In [ ]:
#1.
matriz_o2 = np.array([[1, 2],
                    [3, 4]])

print(matriz_o2)


[[1 2]
 [3 4]]


In [ ]:
#2.
matriz_o3 = np.array([[1, 2, 1],
                [3, 4, 3],
                [5, 6, 5]])

matriz_o3


array([[1, 2, 1],
       [3, 4, 3],
       [5, 6, 5]])

In [ ]:
#3.
matriz_o4 = np.array([[1,2,3,4],[2,3,4,5],[3,4,5,6],[4,5,6,7]])
matriz_o4

array([[1, 2, 3, 4],
       [2, 3, 4, 5],
       [3, 4, 5, 6],
       [4, 5, 6, 7]])

In [ ]:
#4.
matriz_i4 = np.eye(4, dtype=int)
matriz_i4

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

In [ ]:
#5.
"""Para a criação de uma matriz de ordem 3 e 4, a unica diferença consiste no parâmetro que você passa para a função.
Isso também serve para a criação das matriz de identidade. A lib numpy é responsável por ordenar todo o esqueleto"""

'Para a criação de uma matriz de ordem 3 e 4, a unica diferença consiste no parâmetro que você passa para a função.\nIsso também serve para a criação das matriz de identidade. A lib numpy é responsável por ordenar todo o esqueleto'

In [ ]:
#6.
"""Para esse exemplo, vou usar a matriz 3x3 que construi no começo"""
det_matriz_o3 = np.linalg.det(matriz_o3)
print(det_matriz_o3)

-1.7763568394002396e-15


In [ ]:
#7.
matriz_nula = np.array([[4, 6],[2,3]])
matriz_det0 = np.linalg.det(matriz_nula)
matriz_det0

np.float64(0.0)

In [ ]:
#8.
matriz_a = sp.Matrix([[1,2,3],[2,3,4],[3,4,5]])
vetor_b = sp.Matrix([9,13,17])

matriz_aumentada_AB = matriz_a.row_join(vetor_b)

matriz_AB_escalonada, _ = matriz_aumentada_AB.rref()
matriz_AB_escalonada



Matrix([
[1, 0, -1, -1],
[0, 1,  2,  5],
[0, 0,  0,  0]])